DROP DATABASE IF EXISTS linnet CASCADE;
CREATE DATABASE IF NOT EXISTS linnet;
SET DATABASE = linnet;


CREATE TABLE IF NOT EXISTS users (
  id SERIAL NOT NULL PRIMARY KEY,
  email VARCHAR NOT NULL UNIQUE,
  username VARCHAR NOT NULL UNIQUE
);